# Generated by Django 4.0.4 on 2022-06-01 14:19

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('slug', models.SlugField(max_length=25, primary_key=True, serialize=False, verbose_name='Slug')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('icon', models.CharField(max_length=15, verbose_name='Icon')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('submenu_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Submenu compound id')),
                ('slug', models.SlugField(max_length=25, verbose_name='Slug')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('icon', models.CharField(max_length=15, verbose_name='Icon')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.menu')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.CharField(max_length=75, primary_key=True, serialize=False, verbose_name='Page compound id')),
                ('slug', models.SlugField(max_length=25, verbose_name='Slug')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.CharField(max_length=200)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, size=[345, 261], upload_to='images/page/')),
                ('markdown_text', models.TextField(verbose_name='Markdown text')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.submenu')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='default_submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_submenu_option', to='core.submenu'),
        ),
        migrations.AddConstraint(
            model_name='submenu',
            constraint=models.UniqueConstraint(fields=('slug', 'menu'), name='Submenu compound id'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('slug', 'submenu'), name='Page compound id'),
        ),
    ]
